package com.giomatic.entities.remote;
// Generated Apr 19, 2017 4:55:40 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * AppFdInventory generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "app_fd_inventory", catalog = "geomatic")
public class AppFdInventory implements java.io.Serializable {

	private String id;
	private Date dateCreated;
	private Date dateModified;
	private String CKodeBarang;
	private String CNamaBarang;
	private String CNo;
	private String CSatuan;
	private String CKwantum;
	private String CUkuran;
	private String CHarga;

	public AppFdInventory() {
	}

	public AppFdInventory(String id) {
		this.id = id;
	}

	public AppFdInventory(String id, Date dateCreated, Date dateModified, String CKodeBarang, String CNamaBarang,
			String CNo, String CSatuan, String CKwantum, String CUkuran, String CHarga) {
		this.id = id;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.CKodeBarang = CKodeBarang;
		this.CNamaBarang = CNamaBarang;
		this.CNo = CNo;
		this.CSatuan = CSatuan;
		this.CKwantum = CKwantum;
		this.CUkuran = CUkuran;
		this.CHarga = CHarga;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreated", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateModified", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "c_kode_barang")
	public String getCKodeBarang() {
		return this.CKodeBarang;
	}

	public void setCKodeBarang(String CKodeBarang) {
		this.CKodeBarang = CKodeBarang;
	}

	@Column(name = "c_nama_barang")
	public String getCNamaBarang() {
		return this.CNamaBarang;
	}

	public void setCNamaBarang(String CNamaBarang) {
		this.CNamaBarang = CNamaBarang;
	}

	@Column(name = "c_no")
	public String getCNo() {
		return this.CNo;
	}

	public void setCNo(String CNo) {
		this.CNo = CNo;
	}

	@Column(name = "c_satuan")
	public String getCSatuan() {
		return this.CSatuan;
	}

	public void setCSatuan(String CSatuan) {
		this.CSatuan = CSatuan;
	}

	@Column(name = "c_kwantum")
	public String getCKwantum() {
		return this.CKwantum;
	}

	public void setCKwantum(String CKwantum) {
		this.CKwantum = CKwantum;
	}

	@Column(name = "c_ukuran")
	public String getCUkuran() {
		return this.CUkuran;
	}

	public void setCUkuran(String CUkuran) {
		this.CUkuran = CUkuran;
	}

	@Column(name = "c_harga")
	public String getCHarga() {
		return this.CHarga;
	}

	public void setCHarga(String CHarga) {
		this.CHarga = CHarga;
	}

}
